name: Build Zygisk-Loader

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Target app package name"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # 安装 NDK 工具链
      - name: Setup NDK
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake llvm clang

      # 编译项目
      - name: Build
        run: |
          make

      # 写入你输入的包名
      - name: Configure target package
        run: |
          mkdir -p config
          echo "${{ github.event.inputs.package_name }}" > config/target

      # 上传成品模块
      - name: Upload module
        uses: actions/upload-artifact@v4
        with:
          name: Zygisk-Loader-Module
          path: |
            *.so
            zygisk/
            config/
            module.prop
            META-INF/
            *.zip

