name: Build Zygisk-Loader

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Target app package name"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 自动创建 config，写入你输入的包名
      - name: Create config
        run: |
          mkdir -p config
          echo "${{ github.event.inputs.package_name }}" > config/target

      # 直接把整个模块打包上传
      - name: Upload full module
        uses: actions/upload-artifact@v4
        with:
          name: Zygisk-Loader
          path: |
            ./
            !.git/
